name: Artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out the code
        uses: actions/checkout@2
      - name: Upload the artifacts
        uses: actions/upload-artifact@2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
        
